"""
Django settings for pyoupyou project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/

"""

import os
from django.utils.translation import gettext_lazy as _
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_bleach",
    "crispy_forms",
    "django_tables2",
    "bootstrap",
    "fontawesome",
    "django_select2",
    "ref.apps.RefConfig",
    "interview.apps.InterviewConfig",
    "django_filters",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "pyoupyou.middleware.ExternalCheckMiddleware",
    "pyoupyou.middleware.GlobalSubsidiaryFilterMiddleware",
]

ROOT_URLCONF = "pyoupyou.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ]
        },
    }
]

WSGI_APPLICATION = "pyoupyou.wsgi.application"

AUTH_USER_MODEL = "ref.PyouPyouUser"

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (BASE_DIR / "locale/",)

CRISPY_TEMPLATE_PACK = "bootstrap3"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

MINUTE_FORMAT = (("md", "Markdown"), ("rst", "ReStructured Text"))

STALE_DAYS = 7

USE_X_FORWARDED_HOST = True

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Process analysis financial starting date.
# It should only contain the month and day using '<month>-<day>' format.
FINANCIAL_STARTING_MONTH_DAY = "07-01"


def get_refusal_email_content():
    return {
        str(_("Profile not relevant")): [
            str(_("Answer to your job application")),
            str(
                _(
                    "Hello,\n\nThank you for taking the time to interview with us, "
                    "we appreciate your interest in joining our company."
                    "\nAfter careful consideration, "
                    "we have decided to move forward with another candidate whose experience more closely aligns with our current needs. "
                    "\nThis was a difficult decision given the strong pool of applicants."
                    "\nWe wish you the best in your job search and future endeavors."
                    "\n\nBest regards,"
                )
            ),
        ],
        str(_("No open positions")): [
            str(_("Answer to your job application")),
            str(
                _(
                    "Hello,\n\nThank you for taking the time to interview with us, "
                    "we appreciate your interest in joining our company."
                    "\nWe regretfully inform you that we are currently unable to accept any further applications at this time."
                    "\nWe wish you the best in your job search and future endeavors."
                    "\n\nBest regards,"
                )
            ),
        ],
        str(_("Missing contact information")): [
            str(_("Answer to your job application")),
            str(
                _(
                    "Hello,\n\nThank you for taking the time to interview with us, "
                    "we appreciate your interest in joining our company."
                    "\nUnfortunately, we are unable to proceed with your application at this time due to missing contact information."
                    "\nIf you are interested in joining our team, please ensure you have provided all the necessary information."
                    "\n\nBest regards,"
                )
            ),
        ],
    }
