# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:34
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trigramme', models.CharField(max_length=4, unique=True)),
                ('productive', models.BooleanField(default=True, verbose_name='Productive')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Subsidiary',
                'verbose_name_plural': 'Subsidiaries',
            },
        ),
        migrations.AddField(
            model_name='consultant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.Subsidiary', verbose_name='Subsidiary'),
        ),
    ]
