# Generated by Django 3.1.13 on 2021-10-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ref", "0002_auto_20190613_1737")]

    operations = [migrations.RemoveField(model_name="consultant", name="productive")]
