# Generated by Django 3.2.16 on 2022-11-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0003_remove_consultant_productive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultant",
            options={"ordering": ("user__trigramme",)},
        ),
    ]
