# Generated by Django 3.2.16 on 2022-11-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0020_auto_20221104_1703"),
        ("ref", "0004_alter_consultant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="limited_to_source",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="interview.sources",
            ),
        ),
    ]
