# Generated by Django 3.2.16 on 2022-11-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0020_auto_20221104_1703"),
        ("ref", "0004_alter_consultant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="limited_to_source",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="interview.sources",
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="privilege",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "User is an insider consultant"),
                    (2, "User is an external consultant"),
                    (3, "User is external and has only read rights"),
                ],
                default=1,
                verbose_name="Authority level",
            ),
        ),
    ]
