# Generated by Django 3.2.16 on 2022-11-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0020_auto_20221104_1703'),
        ('ref', '0004_alter_consultant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='to_source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.sources'),
        ),
    ]
