# Generated by Django 3.2.16 on 2022-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0005_consultant_limited_to_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="privilege",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "User is an insider consultant"),
                    (2, "User is an external consultant"),
                    (3, "User is external and has only read rights"),
                ],
                default=1,
                verbose_name="Authority level",
            ),
        ),
    ]
