# Generated by Django 3.2.16 on 2023-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0005_auto_20221122_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="privilege",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "User is an insider consultant"),
                    (2, "User is an external consultant with additional rights"),
                    (3, "User is an external consultant"),
                    (4, "User is external and has only read rights"),
                ],
                default=1,
                verbose_name="Authority level",
            ),
        ),
    ]
