# Generated by Django 3.2.16 on 2023-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0006_alter_consultant_privilege"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidiary",
            name="informed",
            field=models.ManyToManyField(
                blank=True,
                related_name="subsidiary_notifications",
                to="ref.Consultant",
                verbose_name="Informed consultants",
            ),
        ),
    ]
