# Generated by Django 4.2.4 on 2024-01-09 10:17

from django.db import migrations, models
import ref.models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0007_subsidiary_informed"),
    ]

    operations = [
        migrations.AddField(
            model_name="pyoupyouuser",
            name="token",
            field=models.CharField(blank=True, default=ref.models.generate_token, max_length=50),
        ),
    ]
