# Generated by Django 3.2.16 on 2023-01-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0008_auto_20230116_1656"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Consultant",
        ),
    ]
