# Generated by Django 4.2.4 on 2024-01-09 10:20
import secrets

from django.db import migrations


def generate_token(apps, schema_editor):
    PyouPyouUser = apps.get_model("ref", "PyouPyouUser")
    for user in PyouPyouUser.objects.all():
        user.token = secrets.token_urlsafe(25)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0008_pyoupyouuser_token"),
    ]

    operations = [migrations.RunPython(generate_token)]
