# Generated by Django 3.2.16 on 2023-01-16 15:56
import django
from django.conf import settings
from django.db import migrations, models


def update_informed_and_responsible(apps, schema_editor):
    Subsidiary = apps.get_model("ref", "Subsidiary")
    for subsidiary in Subsidiary.objects.all():
        subsidiary.responsible_new = subsidiary.responsible.user
        subsidiary.informed_new.set([consultant.user for consultant in subsidiary.informed.all()])
        subsidiary.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ref", "0008_auto_20230116_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidiary",
            name="informed_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="subsidiary_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Informed consultants",
            ),
        ),
        migrations.AddField(
            model_name="subsidiary",
            name="responsible_new",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(update_informed_and_responsible),
        migrations.RemoveField(model_name="subsidiary", name="informed"),
        migrations.RemoveField(model_name="subsidiary", name="responsible"),
        migrations.RenameField(model_name="subsidiary", old_name="informed_new", new_name="informed"),
        migrations.RenameField(model_name="subsidiary", old_name="responsible_new", new_name="responsible"),
    ]
