# Generated by Django 4.2.4 on 2024-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0009_auto_20240109_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidiary",
            name="show_in_report_by_default",
            field=models.BooleanField(
                default=True, verbose_name="Show the subsidiary in the report analysis by default"
            ),
        ),
    ]
