# Generated by Django 4.2.4 on 2024-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0009_auto_20240109_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pyoupyouuser",
            name="trigramme",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
