# Generated by Django 4.2.4 on 2024-07-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0010_alter_pyoupyouuser_trigramme"),
        ("ref", "0010_subsidiary_show_in_report_by_default"),
    ]

    operations = []
