# Generated by Django 4.2.4 on 2024-10-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0009_auto_20230116_1656"),
        ("ref", "0011_merge_20240715_1041"),
    ]

    operations = []
