# Generated by Django 4.2.4 on 2024-10-21 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0028_merge_20241021_1741"),
        ("ref", "0012_merge_20241021_1741"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsidiary",
            name="show_in_report_by_default",
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "privilege",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "User is an insider consultant"),
                            (2, "User is an external consultant with additional rights"),
                            (3, "User is an external consultant"),
                            (4, "User is external and has only read rights"),
                        ],
                        default=1,
                        verbose_name="Authority level",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ref.subsidiary",
                        verbose_name="Subsidiary",
                    ),
                ),
                (
                    "limited_to_source",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="interview.sources",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ("user__trigramme",),
            },
        ),
    ]
