# Generated by Django 4.2.4 on 2024-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0013_remove_subsidiary_show_in_report_by_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidiary",
            name="show_in_report_by_default",
            field=models.BooleanField(
                default=True, verbose_name="Show the subsidiary in the report analysis by default"
            ),
        ),
    ]
