# Generated by Django 5.1.6 on 2026-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0016_delete_consultant"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsidiary",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Full name"),
        ),
    ]
