[tool.black]
line-length = 120

[tool.poetry]
name = "pyoupyou"
version = "1.14.0"
description = "ATS"
authors = [
    "Benjamin Port <benjamin.port@enioka.com>",
    "Arnaud Chirat <arnaud.chirat@enioka.com>",
    "Thomas Cordival <thomas.cordival@enioka.com"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.9"
django-bootstrap-static = ">=3.3.7,<3.4"
django-crispy-forms = "==1.9.1"
django-select2 = "==7.0.3"
django-extensions = "==2.1.6"
django-tables2 = "==2.3.4"
django-ical = "==1.4"
django-markwhat = "==1.6.1"
commonmark = "==0.9.1"
django-bleach = "==0.3.0"
Django = "==3.2.15"
django-split-settings = "==0.3.0"
requests = '==2.26.0 '
django-filter = "==2.4.0"
plotly = "==4.8.2"
numpy = "==1.22.0"
pytz = "==2021.1"
pandas = "==1.2.2"

[tool.poetry.group.dev.dependencies]
black = "==22.8.0"
django-debug-toolbar = "==2.2.1"
factory-boy = "==3.1.0"
tzlocal = "*"
coverage = "*"
django-debug-toolbar-user-panel = {git = "https://github.com/Napoleon-Black/django-debug-toolbar-user-panel.git",rev = "1481b04e0cbbf7db35bf43061883535ef25892f5"}
django-debug-toolbar-request-history = "==0.1.3"

