# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import interview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('has_duration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('CV', 'CV'), ('CL', 'Cover Letter'), ('OT', 'Others')], max_length=2)),
                ('content', models.FileField(upload_to=interview.models.document_path)),
                ('still_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_state', models.CharField(choices=[('PD', 'NEED PLANIFICATION'), ('PL', 'PLANNED'), ('GO', 'GO'), ('NO', 'NO'), ('DGO', 'DONE GO'), ('DNO', 'DONE NO')], max_length=3, verbose_name='next state')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='rank')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='planned date')),
            ],
            options={
                'ordering': ['process', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='InterviewInterviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.TextField(blank=True, verbose_name='minute')),
                ('minute_format', models.CharField(choices=[('md', 'Markdown'), ('rst', 'ReStructured Text')], default='md', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('salary_expectation', models.IntegerField(blank=True, null=True, verbose_name='Salary expectation (k€)')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contract duration in month')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Candidate')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.ContractType')),
            ],
        ),
    ]
