# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='content',
        ),
    ]
