# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20170401_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='rank',
            field=models.IntegerField(null=True, verbose_name='rank'),
        ),
    ]
