# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_subsidiary_responsible'),
        ('interview', '0002_auto_20170404_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='next_state',
            field=models.CharField(choices=[('NP', 'NEED PLANIFICATION'), ('PL', 'PLANIFIED'), ('GO', 'GO'), ('NO', 'NO')], max_length=3, verbose_name='next state'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned date'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Interview', verbose_name='Interview'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.Consultant', verbose_name='Interviewer'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='minute',
            field=models.TextField(blank=True, verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='suggested_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_interview_for', to='ref.Consultant', verbose_name='Suggested interviewer'),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Start date'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together=set([('interview', 'interviewer')]),
        ),
    ]
