# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20170401_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='rank'),
        ),
        migrations.AlterField(
            model_name='interviewinterviewer',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.Consultant', verbose_name='interviewer'),
        ),
    ]
