# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_subsidiary_responsible'),
        ('interview', '0003_auto_20170408_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(through='interview.InterviewInterviewer', to='ref.Consultant'),
        ),
    ]
