# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20170401_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together=set([]),
        ),
    ]
