# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_interviewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SourcesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='process',
            old_name='duration',
            new_name='contract_duration',
        ),
        migrations.AddField(
            model_name='process',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sources',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.SourcesCategory'),
        ),
        migrations.AddField(
            model_name='process',
            name='sources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Sources'),
        ),
    ]
