# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20170402_0905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together=set([('interview',)]),
        ),
    ]
