# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20170408_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.ContractType'),
        ),
        migrations.AlterField(
            model_name='process',
            name='sources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.Sources'),
        ),
    ]
