# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20180325_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='state',
            field=models.CharField(choices=[('OP', 'Open'), ('WA', 'Waiting interviewer to be designed'), ('WK', 'Waiting next interview designation or process termination'), ('JO', 'Waiting candidate feedback after a job offer'), ('WP', 'Waiting interview planification'), ('WM', 'Waiting interview minute'), ('WI', 'Waiting interview'), ('NG', 'Last interviewer interupt process'), ('CD', 'Candidate declined our offer'), ('HI', 'Candidate accepted our offer'), ('NO', 'Closed - other reason')], default='WA', max_length=3, verbose_name='Closed reason'),
        ),
    ]
