# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20180526_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='responsible',
            field=models.ManyToManyField(blank=True, null=True, to='ref.Consultant'),
        ),
    ]
