# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0002_subsidiary_responsible'),
        ('interview', '0007_auto_20170412_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='minute',
            field=models.TextField(blank=True, verbose_name='Minute'),
        ),
        migrations.AddField(
            model_name='interview',
            name='minute_format',
            field=models.CharField(choices=[('md', 'Markdown'), ('rst', 'ReStructured Text')], default='md', max_length=3),
        ),
        migrations.AddField(
            model_name='interview',
            name='suggested_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_interview_for', to='ref.Consultant', verbose_name='Suggested interviewer'),
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewers',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(to='ref.Consultant'),
        ),
    ]
