# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 20:10
from __future__ import unicode_literals

from django.db import migrations


def move_minute(apps, schema_editor):
    Interview = apps.get_model("interview", "Interview")
    InterviewInterviewer = apps.get_model("interview", "InterviewInterviewer")

    # move minute from interview interviewer to interview if an interview as 2 minuts we keep only one
    for i in InterviewInterviewer.objects.exclude(minute__isnull=True).exclude(minute__exact=''):
        interview = Interview.objects.get(id=i.interview_id)
        print(interview.planned_date)
        interview.minute = i.minute
        interview.suggested_interviewer = i.suggested_interviewer
        interview.save()


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20170414_1908'),
    ]

    operations = [
        migrations.RunPython(move_minute),
    ]
