# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20170414_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewinterviewer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='interviewinterviewer',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='interviewinterviewer',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interviewinterviewer',
            name='suggested_interviewer',
        ),
        migrations.DeleteModel(
            name='InterviewInterviewer',
        ),
    ]
