# Generated by Django 2.2.5 on 2019-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("interview", "0010_auto_20191018_1537")]

    operations = [
        migrations.AddField(
            model_name="process",
            name="other_informations",
            field=models.TextField(blank=True, verbose_name="Other informations"),
        )
    ]
