# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_auto_20170414_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='next_interview_goal',
            field=models.TextField(blank=True, verbose_name='Next interview goal'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planned date'),
        ),
    ]
