# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20170416_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='closed_comment',
            field=models.TextField(blank=True, verbose_name='Closed comment'),
        ),
        migrations.AddField(
            model_name='process',
            name='closed_reason',
            field=models.CharField(choices=[('OP', 'Open'), ('NG', 'No'), ('CD', 'Candidate declined our offer'), ('HI', 'Candidate accepted our offer'), ('NO', 'Closed - other reason')], default='OP', max_length=3, verbose_name='Closed reason'),
        ),
    ]
