# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_auto_20170516_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='closed_reason',
            field=models.CharField(choices=[('OP', 'Open'), ('NG', 'Last interviewer interupt process'), ('CD', 'Candidate declined our offer'), ('HI', 'Candidate accepted our offer'), ('NO', 'Closed - other reason')], default='OP', max_length=3, verbose_name='Closed reason'),
        ),
    ]
