# Generated by Django 2.2.13 on 2020-07-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("interview", "0013_auto_20200224_1036")]

    operations = [migrations.AlterModelOptions(name="sources", options={"ordering": ["name"]})]
