# Generated by Django 2.2.12 on 2020-10-08 10:24

from django.db import migrations, models
from interview.models import Candidate as Candidate2


def migrate_state(apps, schema_editor):
    from django.apps import apps

    Candidate = apps.get_model("interview", "Candidate")

    for candidate in Candidate.objects.all():
        candidate.save()


def migrate_state_reverse(apps, schema_editor):
    Candidate = apps.get_model("interview", "Candidate")
    for candidate in Candidate.objects.all():
        candidate.anonymized_hashed_name = ""
        candidate.anonymized_hashed_email = ""
        candidate.anonymized_hashed_phone = ""

        candidate.save()


class Migration(migrations.Migration):

    dependencies = [("interview", "0014_auto_20201201_1832")]

    operations = [
        migrations.AlterModelOptions(name="sources", options={"ordering": ["name"]}),
        migrations.AddField(model_name="candidate", name="anonymized", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name="candidate",
            name="anonymized_hashed_email",
            field=models.CharField(blank=True, max_length=41, verbose_name="Anonymized Hashed Email"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="anonymized_hashed_name",
            field=models.CharField(blank=True, max_length=41, verbose_name="Anonymized Hashed Name"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="anonymized_hashed_phone",
            field=models.CharField(blank=True, max_length=41, verbose_name="Anonymized Hashed Phone"),
        ),
        migrations.RunPython(migrate_state, migrate_state_reverse),
    ]
