# Generated by Django 2.2.12 on 2020-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("interview", "0014_auto_20201201_1832")]

    operations = [
        migrations.AlterModelOptions(name="sources", options={"ordering": ["name"]}),
        migrations.AddField(model_name="candidate", name="anonymized", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name="candidate",
            name="anonymized_hashed_email",
            field=models.CharField(blank=True, max_length=41, verbose_name="Anonymized Hashed Email"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="anonymized_hashed_name",
            field=models.CharField(blank=True, max_length=41, verbose_name="Anonymized Hashed Name"),
        ),
    ]
