# Generated by Django 3.1.13 on 2021-09-16 16:08

from django.db import migrations

import hashlib

from django.conf import settings

import unicodedata


def remove_accents(input_str):
    nfkd_form = unicodedata.normalize("NFKD", input_str)
    only_ascii = nfkd_form.encode("ASCII", "ignore")
    return only_ascii


def anonymize_name(name):
    h = hashlib.sha256()
    h.update(settings.SECRET_ANON_SALT.encode("utf-8"))
    h.update(remove_accents(name.lower()))
    return h.digest()


def anonymize_email(candidate):
    if candidate.email:
        m = hashlib.sha256()
        m.update(settings.SECRET_ANON_SALT.encode("utf-8"))
        m.update(candidate.email.lower().encode("utf-8"))
        return m.digest()
    return ""


def compute_anonymized_fields(candidate):
    if not candidate.anonymized:
        if candidate.name != "":
            candidate.anonymized_hashed_name = anonymize_name(candidate.name)
        if candidate.email != "":
            candidate.anonymized_hashed_email = anonymize_email(candidate)
        if candidate.phone != "":
            candidate.phone = ""


def migrate_state(apps, schema_editor):
    Candidate = apps.get_model("interview", "Candidate")

    for candidate in Candidate.objects.all():
        compute_anonymized_fields(candidate)
        candidate.save()


def migrate_state_reverse(apps, schema_editor):
    Candidate = apps.get_model("interview", "Candidate")
    for candidate in Candidate.objects.all():
        candidate.anonymized_hashed_name = ""
        candidate.anonymized_hashed_email = ""

        candidate.save()


class Migration(migrations.Migration):

    dependencies = [("interview", "0015_candidate_anonymization")]

    operations = [migrations.RunPython(migrate_state, migrate_state_reverse)]
