# Generated by Django 3.2.11 on 2022-02-10 09:51

from django.db import migrations, models
import django.db.models.deletion
import interview.models


class Migration(migrations.Migration):

    dependencies = [("interview", "0019_auto_20211128_1257")]

    operations = [
        migrations.CreateModel(
            name="DocumentInterview",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="Creation date")),
                (
                    "content",
                    models.FileField(upload_to=interview.models.document_minute_path, verbose_name="Content file"),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="interview.interview", verbose_name="Interview"
                    ),
                ),
            ],
        )
    ]
