# Generated by Django 3.1.13 on 2022-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("interview", "0019_auto_20211128_1257")]

    operations = [
        migrations.AddField(
            model_name="interview", name="goal", field=models.TextField(blank=True, verbose_name="Interview goal")
        )
    ]
