# Generated by Django 3.2.16 on 2022-11-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0020_auto_20221104_1703"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="suggested_interviewer",
        ),
    ]
