# Generated by Django 3.2.16 on 2022-11-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0020_interview_goal"),
        ("interview", "0021_remove_interview_suggested_interviewer"),
    ]

    operations = []
