# Generated by Django 3.2.16 on 2022-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0022_merge_20221123_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentinterview",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
    ]
