# Generated by Django 3.2.16 on 2022-12-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0022_merge_20221123_1707"),
        ("interview", "0023_documentinterview_name"),
    ]

    operations = []
