# Generated by Django 3.2.16 on 2022-12-15 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0024_merge_20221212_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_processes", to=settings.AUTH_USER_MODEL, verbose_name="Subscribers"
            ),
        ),
    ]
