# Generated by Django 3.2.16 on 2023-01-16 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0024_merge_20221212_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_creator', to=settings.AUTH_USER_MODEL, verbose_name='Process creator'),
        ),
        migrations.AlterField(
            model_name='process',
            name='responsible',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
