# Generated by Django 3.2.16 on 2023-01-16 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fill_interviewers_and_creator_and_responsible_new(apps, schema_editor):
    Interview = apps.get_model("interview", "Interview")
    for interview in Interview.objects.all():
        interview.interviewers_new.set([consultant.user for consultant in interview.interviewers.all()])
        interview.save()

    for process in apps.get_model("interview", "Process").objects.filter(creator__isnull=False):
        process.creator_new = process.creator.user
        process.responsible_new.set([consultant.user for consultant in process.responsible.all()])
        process.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0024_merge_20221212_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interviewers_new",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="process",
            name="responsible_new",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="process",
            name="creator_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="process_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Process creator",
            ),
        ),
        migrations.RunPython(fill_interviewers_and_creator_and_responsible_new),
        migrations.RemoveField(
            model_name="interview",
            name="interviewers",
        ),
        migrations.RemoveField(
            model_name="process",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="process",
            name="responsible",
        ),
        migrations.RenameField(model_name="process", old_name="creator_new", new_name="creator"),
        migrations.RenameField(model_name="interview", old_name="interviewers_new", new_name="interviewers"),
        migrations.RenameField(model_name="process", old_name="responsible_new", new_name="responsible"),
    ]
