# Generated by Django 3.2.16 on 2023-01-23 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0025_process_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_offers", to=settings.AUTH_USER_MODEL, verbose_name="Subscribers"
            ),
        ),
    ]
