# Generated by Django 3.2.16 on 2023-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0026_offer_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewkind",
            name="medium",
            field=models.URLField(blank=True, null=True),
        ),
    ]
