# Generated by Django 4.2.4 on 2023-08-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0026_offer_subscribers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ("pk",)},
        ),
    ]
