# Generated by Django 4.2.4 on 2024-10-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0025_auto_20230116_1355"),
        ("interview", "0027_alter_offer_options"),
    ]

    operations = []
