# Generated by Django 4.2.4 on 2024-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0027_alter_offer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Contract start date"),
        ),
    ]
