# Generated by Django 4.2.4 on 2025-01-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ref", "0016_delete_consultant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0028_merge_20241021_1741"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsibleRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.IntegerField(default=0)),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="interview.contracttype"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="interview.offer"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "sources",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="interview.sources"
                    ),
                ),
                ("subsidiary", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ref.subsidiary")),
            ],
        ),
    ]
