# Generated by Django 4.2.4 on 2024-10-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0028_alter_process_contract_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("CV", "CV"), ("CL", "Cover Letter"), ("OT", "Other")],
                max_length=2,
                verbose_name="Kind of document",
            ),
        ),
    ]
