# Generated by Django 4.2.4 on 2025-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0028_merge_20241021_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttype",
            name="color",
            field=models.CharField(max_length=7, null=True, blank=True, default="#FFFFFF"),
        ),
    ]
