# Generated by Django 5.1.6 on 2025-02-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0029_contracttype_color"),
        ("interview", "0029_responsiblerule"),
    ]

    operations = []
