# Generated by Django 4.2.4 on 2025-09-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0029_alter_document_document_type"),
        ("interview", "0030_merge_0029_contracttype_color_0029_responsiblerule"),
    ]

    operations = []
