# Generated by Django 5.1.6 on 2025-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0031_merge_20250918_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="state",
            field=models.CharField(
                choices=[
                    ("OP", "Open"),
                    ("WA", "Waiting interviewer to be designed"),
                    ("WK", "Waiting next interview designation or process termination"),
                    ("JO", "Waiting candidate feedback after a job offer"),
                    ("WP", "Waiting interview planification"),
                    ("WR", "Waiting for interview planification response"),
                    ("WM", "Waiting interview minute"),
                    ("WI", "Waiting interview"),
                    ("NG", "Last interviewer interupt process"),
                    ("CD", "Candidate declined our offer"),
                    ("NR", "Candidate profile not aligned with job offer"),
                    ("HI", "Candidate accepted our offer"),
                    ("NO", "Closed - other reason"),
                ],
                default="WA",
                max_length=3,
                verbose_name="Closed reason",
            ),
        ),
    ]
