# Generated by Django 5.1.6 on 2026-03-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0032_alter_process_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "permissions": [("frontend_can_delete_candidate", "Frontend can delete candidate")],
                "verbose_name": "Candidate",
            },
        ),
        migrations.AlterModelOptions(
            name="process",
            options={"permissions": [("frontend_can_delete_process", "Frontend can delete process")]},
        ),
    ]
