# Generated by Django 5.1.6 on 2026-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0032_alter_process_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblerule",
            name="priority",
            field=models.IntegerField(default=0, help_text="Higher number has priority"),
        ),
    ]
