# Generated by Django 5.1.6 on 2026-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0032_alter_process_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewkind",
            name="email_subject",
            field=models.TextField(blank=True, verbose_name="Email subject"),
        ),
        migrations.AddField(
            model_name="interviewkind",
            name="email_template",
            field=models.TextField(blank=True, verbose_name="Email template"),
        ),
    ]
