# Generated by Django 5.1.6 on 2026-03-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0032_alter_process_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={
                "ordering": ["process", "rank"],
                "permissions": (("frontend_can_plan_interview", "Frontend can plan interview"),),
            },
        ),
    ]
