# Generated by Django 5.1.6 on 2026-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0033_interviewkind_email_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewkind",
            name="attached_ics",
            field=models.BooleanField(default=False, verbose_name="Attached .ics file"),
        ),
        migrations.AddField(
            model_name="interviewkind",
            name="duration",
            field=models.PositiveIntegerField(default=60, verbose_name="Interview duration in minutes"),
        ),
    ]
