# Generated by Django 5.1.6 on 2026-03-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0033_alter_candidate_options_alter_process_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="process",
            options={
                "permissions": [("frontend_can_delete_process", "Frontend can delete process")],
                "verbose_name": "Process",
            },
        ),
    ]
