# Generated by Django 5.1.6 on 2026-09-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0033_alter_responsiblerule_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="process",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="interview.process",
                verbose_name="Process",
            ),
        ),
    ]
