# Generated by Django 5.1.6 on 2026-03-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0034_alter_process_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interview",
            options={
                "ordering": ["process", "rank"],
                "permissions": [("frontend_can_delete_interview", "Frontend can delete interview")],
                "verbose_name": "Interview",
            },
        ),
    ]
