name: Django CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PYOUPYOU_ENV: dev
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install the project
        run: uv sync --dev
      - name: Check migrations
        run: uv run ./manage.py makemigrations --check
      - name: Check coding style (black)
        run: uv run black --check .
      - name: Check requirements.txt is up to date
        run: |
          uv export --format requirements-txt --no-header --no-dev --no-hashes --frozen|diff requirements.txt -
  test:
    runs-on: ubuntu-latest
    env:
      PYOUPYOU_ENV: dev
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: pyoupyou
        ports: [ '3306:3306' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv sync --dev --group=mysql
      - name: test
        run: |
          cp pyoupyou/settings/local.py.ci pyoupyou/settings/local.py
          uv run coverage run ./manage.py test
