name: Django CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PYOUPYOU_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - name: Check migrations
        run: poetry run ./manage.py makemigrations --check
      - name: Check coding style (black)
        run: poetry run black --check .
      - name: Check requirements.txt is up to date
        run: |
          poetry export --without-hashes -f requirements.txt|diff requirements.txt -
  test:
    runs-on: ubuntu-latest
    env:
      PYOUPYOU_ENV: dev
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: pyoupyou
        ports: [ '3306:3306' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install --no-interaction
      - name: test
        run: |
          cp pyoupyou/settings/local.py.ci pyoupyou/settings/local.py
          poetry run pip install mysqlclient
          poetry run coverage run ./manage.py test
